config/routes.rb
BestLocator::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace 'api' do
    namespace 'v1' do
      resources :routes
      resources :location_reports
      resources :bus_stops do
        member do
          get 'arrivals'
        end
      end
      resources :trips do
        member do
          put 'stop'
          put 'start'
        end
        collection do
          get 'live'
        end
      end
      resources :users
      resources :sessions, only: [:create, :destroy]
      resources :browse do
        collection do
          get 'map_squares'
          get 'areas'
          get 'bus_stops'
          get 'route'
        end
      end
    end
  end


  resources :trips
  resources :routes
  resources :users do
    resources :trips
  end

  match '/profile', :to => 'users#profile', :via => "get"

  root "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable

  before_validation :verify_token_exists

  has_many :trips

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.email = auth.info.email
      user.name = [auth.info.first_name, auth.info.last_name].join(" ")
      user.set_oauth_password
    end
  end


  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def has_live_trip?
    self.trips.where(:status => "started").count > 0
  end

  def set_oauth_password
    return nil unless uid
    return nil if self.encrypted_password
    self.password = self.password_confirmation = Digest::SHA1.hexdigest("#{self.uid}--#{ENV['OAUTH_PASSWORD_SALT']}")[0..9]
  end


  private

  def verify_token_exists
    self.auth_token ||= SecureRandom::urlsafe_base64
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  before_filter :authenticate_user_from_token!, except: :create
  before_filter :authenticate_user!, except: :create

  protect_from_forgery except: :create

  def show
    @user = current_user
    respond_to do |format|
      format.json { render json: @user.to_json}
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user.to_json
    else
      render json: @user.errors, status: 422
    end
  end


  private

  def user_params
    params.require("user").permit("email","password","password_confirmation")
  end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = current_user
  end

end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.haml
= javascript_include_tag "users"
.container
  #app{"ng-app" => "bestLocatorApp"}
    #user{:"ng-controller" => "UsersCtrl"}
      .row
        .col-md-2
          = profile_pic type: "large"
        .col-md-3
          %h2
            {{user.name}}
          %h3
            {{trips.length}} trips
        .col-md-2
          = link_to "Start a trip", new_trip_path, :class => "button btn btn-large btn-info"

      %table.table.table-striped
        %thead
          %tr
            %th Id
            %th From
            %th at
            %th To
            %th at
            %th status
            %th kms
        %tbody
          %tr{:"ng-repeat" => "t in trips" }
            %td {{t.id}}
            %td {{t.start_stop_name}}
            %td {{t.started_at}}
            %td {{t.end_stop_name}}
            %td {{t.ended_at}}
            %td {{t.status}}
            %td {{t.kms}}

app/views/users/show.html.haml
= javascript_include_tag "users"
#app{"ng-app" => "bestLocatorApp"}
  #user{:"ng-controller" => "UsersCtrl"}
    .row
      .col-md-2
        = profile_pic type: "large"
      .col-md-6
        %h2
          {{user.name}}
        %h3
          {{trips.length}} trips

    %table.table.table-striped
      %thead
        %tr
          %th Id
          %th From
          %th To
          %th status
          %th kms
      %tbody
        %tr{:"ng-repeat" => "t in trips" }
          %td
            {{t.id}}
          %td
            {{t.from}}
            {{t.start_time}}
          %td
            {{t.to}}
            {{t.end_time}}
          %td
            {{td.status}}
          %td
            {{td.kms}}