config/routes.rb
BestLocator::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace 'api' do
    namespace 'v1' do
      resources :routes
      resources :location_reports
      resources :bus_stops do
        member do
          get 'arrivals'
        end
      end
      resources :trips do
        member do
          put 'stop'
          put 'start'
        end
        collection do
          get 'live'
        end
      end
      resources :users
      resources :sessions, only: [:create, :destroy]
      resources :browse do
        collection do
          get 'map_squares'
          get 'areas'
          get 'bus_stops'
          get 'route'
        end
      end
    end
  end


  resources :trips
  resources :routes
  resources :users do
    resources :trips
  end

  match '/profile', :to => 'users#profile', :via => "get"

  root "home#index"

end

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56606892-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default{role: "navigation", style: "padding: 0px 20px"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: "/"}
      = image_tag 'header_logo.png', style: "height:50px"
  / Collect the nav links, forms, and other content for toggling
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      -  if current_user
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            = profile_pic(style: "border-radius:50%;")
            = current_user.name
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to "Profile", profile_path
            %li
              = link_to "Log out", destroy_user_session_path, :method => :delete
      - else
        = link_to (image_tag 'fb-login.png'), user_omniauth_authorize_path("facebook")

  / /.navbar-collapse

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BestLocator
    = stylesheet_link_tag    "application", media: "all"
    %script{:src => "http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&key=AIzaSyAua_bhuj4kOzFFX1UtgpqpvrO-ntx9czA"}
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:name => "viewport", :content => "width=device-width", "user-scalable" => "no"}
    %meta{:name => "pusher_app_key", :content => ENV['PUSHER_KEY']}
    = render 'layouts/ga'
  %body
    = render "layouts/nav"
    .container-fluid
      - if flash[:notice]
        .alert.alert-success.alert-dismissable
          %button{:type => "button", :class =>"close", :"data-dismiss" =>"alert", :"aria-hidden" => "true"}
            &times;
          = flash[:notice]
      - if flash[:error]
        .alert.alert-danger.alert-dismissable
          %button{:type => "button", :class =>"close", :"data-dismiss" =>"alert", :"aria-hidden" => "true"}
            &times;
          = flash[:error]
      = yield